print("what do you call a sad strawberry?")
input()
print("a blueberry!!")
input()
print ("would you like to hear another joke?")
answer = input()
if answer == "yes": 
    print("why did the golfer get a new pair of pants?")
    input()
    print("because he got a hole in one!!")
input()
print("what do you call a fake noodle?")
input()
print("an inpasta!!")
input()  
print("why do we tell dad jokes?")
input()
print("because we want you to groan up!!")  
input()
print ("would you like to hear another joke?")
answer = input()
if answer == "yes":
    input()
    print("when does a joke become a dad joke?")
    input()
    print("when it becomes apparent!!")