name = input("What is your name? ")
print(f"Hello {name} and welcome to make your own fill in the blank story!")
input()
answer2 = input ("Before we begin with the story I would like to ask you some questions about yourself is that okay? Yes or No")
if answer2 == "yes" or answer2 == "YES" or answer2 == "Yes":
    print ("Okay Great")
    input()
    animal = input("first question what is your favorite animal? ")
    input
    print(f"I love {animal} too! My favorite animal is a snake especially a anadconda")
    input()
    food = input("second and last question what is your favorite food? ")
    input()
    print(f"I love {food} too! My favorite food is mango") 
    input()
    print("alright then let's jump right in to the fill in the blank story")
    input()
    animal = input("first pick any animal it can be the same one that you answered above: ")
    location = input("now pick a location: ")
    food = input("finaly pick a food: ")
    print("------------------------------------------------------------------------------------------")
    print(f"One day, a {animal} ambled into the {location} and ate a delicious {food} ")
else:
    print("Okay then let's jump right in to the fill in the blank story")
    input()
    animal = input("first pick any animal: ")
    input()
    location = input("now pick a location: ")
    input()
    food = input("finaly pick a food: ")
    input()
    print("------------------------------------------------------------------------------------------")
    print(f"One day, a {animal} ambled into the {location} and ate a delicious {food} ")